<a href="https://colab.research.google.com/github/hruthiksiva/DataScience-Practice/blob/main/practiceset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Libraries we use 

*   matplotlib
*   numpy
*   pandas
*   seaborn
*   scikit-learn
*   scipy
*   statsmodel

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
sales = pd.read_csv('sales_data.csv')

In [ ]:
sales.head()

Date  Day     Month  Year  ...  Unit_Price Profit  Cost Revenue
0  2013-11-26   26  November  2013  ...         120    590   360     950
1  2015-11-26   26  November  2015  ...         120    590   360     950
2  2014-03-23   23     March  2014  ...         120   1366  1035    2401
3  2016-03-23   23     March  2016  ...         120   1188   900    2088
4  2014-05-15   15       May  2014  ...         120    238   180     418

[5 rows x 18 columns]

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   Date              113036 non-null  object
 1   Day               113036 non-null  int64 
 2   Month             113036 non-null  object
 3   Year              113036 non-null  int64 
 4   Customer_Age      113036 non-null  int64 
 5   Age_Group         113036 non-null  object
 6   Customer_Gender   113036 non-null  object
 7   Country           113036 non-null  object
 8   State             113036 non-null  object
 9   Product_Category  113036 non-null  object
 10  Sub_Category      113036 non-null  object
 11  Product           113036 non-null  object
 12  Order_Quantity    113036 non-null  int64 
 13  Unit_Cost         113036 non-null  int64 
 14  Unit_Price        113036 non-null  int64 
 15  Profit            113036 non-null  int64 
 16  Cost              113036 non-null  int

In [ ]:
sales.describe()

Day           Year  ...           Cost        Revenue
count  113036.000000  113036.000000  ...  113036.000000  113036.000000
mean       15.665753    2014.401739  ...     469.318695     754.370360
std         8.781567       1.272510  ...     884.866118    1309.094674
min         1.000000    2011.000000  ...       1.000000       2.000000
25%         8.000000    2013.000000  ...      28.000000      63.000000
50%        16.000000    2014.000000  ...     108.000000     223.000000
75%        23.000000    2016.000000  ...     432.000000     800.000000
max        31.000000    2016.000000  ...   42978.000000   58074.000000

[8 rows x 9 columns]

In [ ]:
sales['Day'].describe()

count    113036.000000
mean         15.665753
std           8.781567
min           1.000000
25%           8.000000
50%          16.000000
75%          23.000000
max          31.000000
Name: Day, dtype: float64

In [ ]:
sales['Customer_Age'].mode()

0    31
dtype: int64

In [ ]:
sales.shape

(113036, 18)

In [ ]:
sales.corr()

Day      Year  Customer_Age  ...    Profit      Cost   Revenue
Day             1.000000 -0.007635     -0.014296  ...  0.004623  0.003329  0.003853
Year           -0.007635  1.000000      0.040994  ... -0.181525 -0.215604 -0.208673
Customer_Age   -0.014296  0.040994      1.000000  ...  0.004319 -0.016013 -0.009326
Order_Quantity -0.002412  0.123169      0.026887  ... -0.238863 -0.340382 -0.312895
Unit_Cost       0.003133 -0.217575     -0.021374  ...  0.741020  0.829869  0.817865
Unit_Price      0.003207 -0.213673     -0.020262  ...  0.749870  0.826301  0.818522
Profit          0.004623 -0.181525      0.004319  ...  1.000000  0.902233  0.956572
Cost            0.003329 -0.215604     -0.016013  ...  0.902233  1.000000  0.988758
Revenue         0.003853 -0.208673     -0.009326  ...  0.956572  0.988758  1.000000

[9 rows x 9 columns]

In [ ]:
sales['Revenue Per Age']=sales['Revenue']/sales['Customer_Age']

In [ ]:
sales.head()

Date  Day     Month  Year  ...  Profit  Cost Revenue Revenue Per Age
0  2013-11-26   26  November  2013  ...     590   360     950       50.000000
1  2015-11-26   26  November  2015  ...     590   360     950       50.000000
2  2014-03-23   23     March  2014  ...    1366  1035    2401       49.000000
3  2016-03-23   23     March  2016  ...    1188   900    2088       42.612245
4  2014-05-15   15       May  2014  ...     238   180     418        8.893617

[5 rows x 19 columns]

In [22]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [33]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
a=np.linspace(1,2,9)

In [27]:
a.shape

(9,)

In [30]:
a.dtype

dtype('float64')

In [31]:
a[1:3]

array([1.125, 1.25 ])

In [35]:
b=np.array(([1,2,3],[4,5,6],[7,8,9]),dtype=int)

In [36]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
b[1,2]

6

In [38]:
b[1]

array([4, 5, 6])

In [39]:
b.sum()

45

In [40]:
b[1].sum()

15

In [42]:
b.sum(axis=1)

array([ 6, 15, 24])

In [43]:
b.sum(axis=0)

array([12, 15, 18])

Broadcasting

In [45]:
a=np.arange(4)

In [46]:
a

array([0, 1, 2, 3])

In [47]:
a+10

array([10, 11, 12, 13])

In [48]:
l=[1,2,3]

In [50]:
[i for i in l]

[1, 2, 3]

In [51]:
l[-1]

3

In [52]:
l[-2]

2

Pandas Series

In [56]:
import numpy as np
import pandas as pd


pop=pd.Series([1,2,3,4,5,6,7,8])

In [57]:
pop

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [58]:
pop.name ="Hruthik"

In [59]:
pop

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
Name: Hruthik, dtype: int64

In [60]:
pop.describe()

count    8.00000
mean     4.50000
std      2.44949
min      1.00000
25%      2.75000
50%      4.50000
75%      6.25000
max      8.00000
Name: Hruthik, dtype: float64

In [61]:
pop.index=[
           'Canada',
           'Russia',
           'india',
           'Japan',
           'United Kingdom',
           'United States',
           'Pakistan',
           'France'
]

In [62]:
pop

Canada            1
Russia            2
india             3
Japan             4
United Kingdom    5
United States     6
Pakistan          7
France            8
Name: Hruthik, dtype: int64

In [64]:
pop.iloc[-1]

8

In [65]:
pop >5

Canada            False
Russia            False
india             False
Japan             False
United Kingdom    False
United States      True
Pakistan           True
France             True
Name: Hruthik, dtype: bool

In [66]:
pop.mean()

4.5

In [73]:
df=pd.DataFrame({
    'Pap':[1,2,3,4,6,7,8,9],
    'GDP':[9,8,7,6,5,4,3,2],
    'Area':[2,4,6,8,10,12,14,17]
},columns=['A','B','C','D'])

In [74]:
df

Empty DataFrame
Columns: [A, B, C, D]
Index: []